# encoding: UTF-8
ENV["RAILS_ENV"] = "test"
require File.expand_path(File.dirname(__FILE__) + "/test/rails/config/environment")

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'

Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'HumpyardForm'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('doc/**/*.rdoc', 'lib/**/*.rb', 'app/*/humpyard_form/**/*.rb')
  rdoc.rdoc_files.exclude('lib/generators/**/templates/**/*.rb')
end

begin
  require 'rspec'
  require 'rspec/core/rake_task'

  Rspec::Core::RakeTask.new(:spec)
  
  namespace :spec do
    desc "Run specs to generate coverage"
    Rspec::Core::RakeTask.new(:rcov) do |spec|
      spec.rcov = true
      spec.rcov_opts = %[--exclude "core,expectations,gems/*,spec/resources,spec/spec,spec/spec_helper.rb,/Library/Ruby/*,config/*" --text-summary  --sort coverage]
    end
  end
rescue
  task :spec do
    abort 'Spec is not available. In order to run features, you must: sudo gem install rspec'
  end
end

begin
  require 'cucumber/rake/task'
  Cucumber::Rake::Task.new(:features)
  
  namespace :features do
    desc "Run features to generate coverage"
    Cucumber::Rake::Task.new(:rcov) do |features|    
      features.rcov = true
      features.rcov_opts = %w{--rails --exclude osx\/objc,gems\/,spec\/,features\/,test\/ --aggregate coverage.data}
      features.rcov_opts << %[-o "coverage"]
    end
  end
rescue LoadError
  task :features do
    abort 'Cucumber is not available. In order to run features, you must: sudo gem install cucumber'
  end
end

desc "Run RSpec and Cucumber tests"
task :test => [:spec, :features]
task :default => :test
 
desc "Run both specs and features to generate aggregated coverage"
task :rcov do |t|
  rm "coverage.data" if File.exist?("coverage.data")
  Rake::Task['spec:rcov'].invoke
  Rake::Task["features:rcov"].invoke
  `open #{File.dirname(__FILE__)}/coverage/index.html`
end

spec = Gem::Specification.new do |s|
  s.name = "humpyard_form"
  s.summary = %Q{HumpyardForm is a Rails form builder}
  s.description = %Q{HumpyardForm is an form builder for Rails 3 applications. It is developed as part of the humpyard cms}
  s.email = 'info@humpyard.org'
  s.homepage = 'http://humpyard.org/'
  s.authors = ['Sven G. Broenstrup', 'Andreas Pieper']
  s.files = Dir["{lib}/**/*", "{app}/*/humpyard_form/**/*", "{config}/locales/*", "{compass}/**/*", "VERSION", "README*", "LICENCE", "Gemfile"]
  s.version = ::File.read(::File.join(::File.dirname(__FILE__), "VERSION")).strip
#  s.add_development_dependency 'rspec', '>= 1.2.9'
#  s.add_development_dependency 'cucumber', '>= 0.6.3'
#  s.add_development_dependency 'cucumber-rails', '>= 0.3.0'
#  s.add_development_dependency 'pickle', '>= 0.2.4'
#  s.add_development_dependency 'capybara', '>= 0.3.5'
#  s.add_development_dependency 'factory_girl', '>= 1.2.3'
#  s.add_development_dependency 'markup_validity', '>= 1.1.0'
  s.add_dependency 'builder'
  s.add_dependency 'rails', '>= 3.0.0.beta'
  s.add_dependency 'haml', '>= 2.2.20'
  s.add_dependency 'acts_as_tree', '>= 0.1.1'
  s.add_dependency 'cancan', '>= 1.1.1'
  s.add_dependency 'globalize2', '>= 0.2.0'
end

Rake::GemPackageTask.new(spec) do |pkg|
end

desc "Create a stand-alone gemspec"
task :gemspec  do
  open("#{spec.name}.gemspec", "w") do |f| 
    f.puts "# Generated by rake\n# DO NOT EDIT THIS FILE DIRECTLY\n"
    f.puts spec.to_ruby 
  end
end

task :gem => [:gemspec]

desc "Install the gem #{spec.name}-#{spec.version}.gem"
task :install do
  system("gem install pkg/#{spec.name}-#{spec.version}.gem --no-ri --no-rdoc")
end
task :install => [:gem]
