# encoding: UTF-8
ENV["RAILS_ENV"] = "test"
require File.expand_path(File.dirname(__FILE__) + "/test/rails/config/environment")

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'

namespace :db do
  namespace :test do
    task :prepare do
      ActiveRecord::Base.configurations = Rails::Application.config.database_configuration      
      ActiveRecord::Base.establish_connection(ActiveRecord::Base.configurations['test'])
      ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
      ActiveRecord::Migrator.migrate("#{File.dirname(__FILE__)}/test/rails/db/migrate/", ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
    end
    desc "Remove the test database"
    task :drop do
      require 'pathname'
      config = Rails::Application.config.database_configuration['test']
      path = Pathname.new(config['database'])
      file = path.absolute? ? path.to_s : File.join(Rails.root, path)

      FileUtils.rm(file)
    end
    desc "Reset the test database and prepare it through scripts in db/migrate"
    task :reset => [:drop, :prepare]
  end
end

Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'HumpyardForm'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('doc/**/*.rdoc', 'lib/**/*.rb', 'app/*/humpyard_form/**/*.rb')
  rdoc.rdoc_files.exclude('lib/generators/**/templates/**/*.rb')
end

begin
  require 'rspec'
  require 'rspec/core/rake_task'

  Rspec::Core::RakeTask.new(:spec)
  
  namespace :spec do
    desc "Run specs to generate coverage"
    Rspec::Core::RakeTask.new(:rcov) do |spec|
      spec.rcov = true
      spec.rcov_opts = %[--exclude "core,expectations,gems/*,spec/resources,spec/spec,spec/spec_helper.rb,/Library/Ruby/*,config/*" --text-summary  --sort coverage]
    end
  end
  
  task :spec => [:'db:test:reset']
rescue
  task :spec do
    abort 'Spec is not available. In order to run cucumber, you must: sudo gem install rspec'
  end
end

begin
  require 'cucumber/rake/task'
  Cucumber::Rake::Task.new(:cucumber)
  
  namespace :cucumber do
    desc "Run cucumber to generate coverage"
    Cucumber::Rake::Task.new(:rcov) do |cucumber|    
      cucumber.rcov = true
      cucumber.rcov_opts = %w{--rails --exclude osx\/objc,gems\/,spec\/,features\/,test\/ --aggregate coverage.data}
      cucumber.rcov_opts << %[-o "coverage"]
    end
    
    task :cucumber => [:'db:test:reset']
  end
rescue LoadError
  task :cucumber do
    abort 'Cucumber is not available. In order to run cucumber, you must: sudo gem install cucumber'
  end
end

desc "Run RSpec and Cucumber tests"
task :test => [:spec, :cucumber]
task :default => :test
 
desc "Run both rspec and cucumber tests to generate aggregated coverage"
task :rcov do |t|
  rm "coverage.data" if File.exist?("coverage.data")
  Rake::Task['spec:rcov'].invoke
  Rake::Task["cucumber:rcov"].invoke
  `open #{File.dirname(__FILE__)}/coverage/index.html`
end

spec = Gem::Specification.new do |s|
  s.name = "humpyard_form"
  s.summary = %Q{HumpyardForm is a Rails form builder}
  s.description = %Q{HumpyardForm is an form builder for Rails 3 applications. It is developed as part of the humpyard cms}
  s.email = 'info@humpyard.org'
  s.homepage = 'http://humpyard.org/'
  s.authors = ['Sven G. Broenstrup', 'Andreas Pieper']
  s.files = Dir["{lib}/**/*", "{app}/*/humpyard_form/**/*", "{config}/locales/*", "{compass}/**/*", "VERSION", "README*", "LICENCE", "Gemfile"]
  s.version = ::File.read(::File.join(::File.dirname(__FILE__), "VERSION")).strip
#  s.add_development_dependency 'rspec', '>= 2.0.0.beta.8'
#  s.add_development_dependency 'cucumber', '>= 0.7.2'
#  s.add_development_dependency 'cucumber-rails', '>= 0.3.0'
#  s.add_development_dependency 'pickle', '>= 0.2.4'
#  s.add_development_dependency 'capybara', '>= 0.3.5'
#  s.add_development_dependency 'factory_girl', '>= 1.2.3'
#  s.add_development_dependency 'markup_validity', '>= 1.1.0'
  s.add_dependency 'builder'
  s.add_dependency 'rails', '>= 3.0.0.beta3'
  s.add_dependency 'haml', '>= 3.0.0.rc.4'
  s.add_dependency 'compass', '>= 0.10.0.rc5'
  s.add_dependency 'cancan', '>= 1.1.1'
  s.add_dependency 'globalize2', '>= 0.2.0'
end

Rake::GemPackageTask.new(spec) do |pkg|
end

desc "Create a stand-alone gemspec"
task :gemspec  do
  open("#{spec.name}.gemspec", "w") do |f| 
    f.puts "# Generated by rake\n# DO NOT EDIT THIS FILE DIRECTLY\n"
    f.puts spec.to_ruby 
  end
end

task :gem => [:gemspec]

desc "Install the gem #{spec.name}-#{spec.version}.gem"
task :install do
  system("gem install pkg/#{spec.name}-#{spec.version}.gem --no-ri --no-rdoc")
end
task :install => [:gem]
