source 'http://gemcutter.org'

gem 'rails',         :git => 'git://github.com/rails/rails.git'
gem 'builder'
gem 'haml',          :git => 'git://github.com/nex3/haml.git'
gem 'compass',       :git => 'git://github.com/chriseppstein/compass.git'
gem 'cancan',        '>= 1.1.1'


# This should be only enabled when the Rails app is standalone:
# gem 'humpyard_form',      :git => 'git://github.com/starpeak/humpyard_form.git'
gem 'sqlite3-ruby',  :require => 'sqlite3'

