source 'http://rubygems.org'

gem "rails",              '>=3.0.0'
gem 'haml',               '>=3.0.0'
gem 'compass',            '>=0.10.0'
gem 'globalize3',         '>=0.0.7'


# This should be only enabled when the Rails app is standalone:
# gem 'humpyard_form',      :git => 'git://github.com/starpeak/humpyard_form.git'
gem 'sqlite3-ruby',  :require => 'sqlite3'

