source 'http://gemcutter.org'

gem "rails",         '>= 3.0.0.beta3'
gem 'haml',          '>= 3.0.0.rc.4'
gem 'compass',       '>= 0.10.0.rc5'
gem 'cancan',        '>= 1.1.1'


# This should be only enabled when the Rails app is standalone:
# gem 'humpyard_form',      :git => 'git://github.com/starpeak/humpyard_form.git'
gem 'sqlite3-ruby',  :require => 'sqlite3'

